# -*- Makefile -*-
EXE = tests/tests
default: 
all: $(EXE)
test: all
	$(EXE)

$(EXE): src/qcheck-ver.sml
	$(MLTON) -output $@ tests/tests.cm

mostlyclean:

clean: mostlyclean
	$(RM) $(EXE)

realclean: clean

include Makefile.version
