structure I = TestFromToString(IntFromTo(Int))
structure I = TestFromToString(IntFromTo(Int4))
structure I = TestFromToString(IntFromTo(Int8))
structure I = TestFromToString(IntFromTo(Int16))
structure I = TestFromToString(IntFromTo(Int32))
structure I = TestFromToString(IntFromTo(Int64))
structure I = TestFromToString(IntFromTo(IntInf))
structure I = TestFromToString(IntFromTo(LargeInt))
